Add tests for RevUserController
RevAssure/P3_Backend pull request #63
Opened 2021-09-23 20:23 UTC by RyanBusby

Disabled the tests that should pass but don't due to the `expect(jsonPath("$").isNotEmpty())` problem.
There are also some updates to the URIGuide in this pull request.

2021-09-23 21:16 UTC, DDRIV approved these changes
documentation present, tests look like tests

2021-09-24 05:48 UTC, cptvictor requested changes
don't use @Disabled, comment out bad lines instead

2021-09-24 05:48 UTC, cptvictor commented on src/test/java/com/revature/RevAssure/controller/RevUserControllerTest.java
> +    @Disabled
comment out/get rid of @Disabled, comment out troublesome lines instead

2021-09-24 14:37 UTC, RyanBusby commented on src/test/java/com/revature/RevAssure/controller/RevUserControllerTest.java
> +    @Disabled
changes have been made.

2021-09-24 15:03 UTC, cptvictor approved these changes
lgtm

2021-09-24 15:05 UTC, DDRIV approved these changes
same as before

2021-09-24 15:05 UTC, merged